graph TD
    A([start]) --> B[open page ARB Tracker Dashboard]
    B --> C[tampilkan filter followup yang belum selesai per project]
    C --> D[tampilkan filter project range tanggal dibuat atau tanggal followup atau tanggal update]
    D --> E([selesai])