graph TD
    A([start]) --> B[open page ARB Tracker Dashboard]
    B --> C[tampilkan jumlah followup yang perlu dilakukan per project, pisahkan antara yang sudah selesai (warna hijau) dan belum selesai (warna merah)]
    C --> D([selesai])