graph TD
    A([start]) --> B[open page ARB Tracker Dashboard]
    B --> C[isi filter untuk mencari project dengan kriteria nama project]
    C --> D[click tombol search]
    D --> E[tampilkan list project yang sesuai dengan kriteria yang diinput]
    E --> F([selesai])