graph TD
    A([start]) --> B[open page ARB Tracker Dashboard.]
    B --> C[pilih salah satu project. klik tombol edit project.]
    C --> D[pada page edit project. pilih salah satu Follow-up Tasks.]
    D --> E[/isikan pada field Action (Rich Text Editor) dan Attachments Paste image or click to upload Click to upload or press Ctrl+V to paste.]
    E --> F[/klik tombol checklist untuk merubah status menjadi selesai.]
    F --> G[klik tombol simpan]
    G --> H([selesai])