graph TD
    A([Mulai]) --> B[Buka Halaman Executive Side Quest Tracker]
    B --> C[Klik 'View Details' pada Side Quest]
    C --> D[Masuk ke Halaman Detail Side Quest, urutkan followup history berdasarkan tanggal descending, buka toggle 'Show Followup History untuk followup history yang terbaru]
    D --> E([selesai])